### ISSUE TITLE
关于相机编号、训练和损失函数

### ISSUE THREAD

**Issue by Dragon2938734** [Kairobo/PaFF#3]
请问我处理的图片名称中包含的相机编号分别为54138969、55011271、58860488、60457274，请问这就对应是cam1、cam2、cam3、cam4嘛？

另外，还想请问贵组实验时是采用了什么的算力呢（比如几张3090或4090？），大概训练耗时多久呢？

另外由于是多视角同时输入，是否损失函数也是考虑了多视角呢？好像arxiv论文中没有详细指出损失函数 

谢谢

**Comment by Kairobo** [comment]
https://kairobo.github.io/PaFF/ 可以从这里下载supplementary，里面有后两个问题的答案。两个训练大概得各跑一天半吧，
cam 编号顺序可以随机，suppl中有视角选择的实验，也可以按你所说的（我们也是用你所说的这个顺序）
