### ISSUE TITLE
关于相机参数的使用

### ISSUE THREAD

**Issue by Dragon2938734** [Kairobo/PaFF#4]
您好，请问你们使用的相机参数中平移矩阵T和gt中的关键点坐标数量级差距过大如何解决呢？因为我数据中关键点坐标都是1e-1（0.1）的数量级，但是平移矩阵T都是1e+3（1000）的数量级，此时做 XR+T 的坐标系转换时会不会由于数量级相差极大导致出错呢，你们如何解决这个问题呢？

谢谢！

**Comment by Kairobo** [comment]
我们没有检测关键点，是靠regression直接align的，所以没有这个数量级关系问题

**Comment by Kairobo** [comment]
正常关键点检测也不会有这个问题，因为一时focal length投影会使这一尺度趋向于一致，还有就是care更多的是residual error，所以尺度上都是差不多的。

**Comment by Dragon2938734** [comment]
明白了，谢谢！
