### ISSUE TITLE
mpi_inf_3dph数据集

### ISSUE THREAD

**Issue by Dragon2938734** [Kairobo/PaFF#5]
您好请问你们使用mpi_inf_3dph时有没有smpl的参数呢，因为在官网上下载的mpi_inf_3dph数据集好像没有smpl的参数，如果没有的话，请问你们训练的时候是如何训练的呢？谢谢

**Comment by Kairobo** [comment]
对，mpi_inf_3dhp没有smpl参数，我只是用它的3d joints，然后加了shape上的regularization让它不要变得太细长。
